# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbCm-upnc7c7XAgbIyv2t1I41zg3jhBT
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np

st.title("Market Regime-Aware RL Portfolio")

initial_capital = st.number_input("Initial Capital", value=100000)
transaction_cost = st.slider("Transaction Cost (%)", 0.0, 1.0, 0.1)

if st.button("Run Simulation"):

    st.write("Running RL Strategy...")

    # Display final metrics
    st.write("Final Portfolio Value:", equity_curve[-1])
    st.write("CAGR:", cagr)
    st.write("Sharpe Ratio:", sharpe)
    st.write("Max Drawdown:", mdd)

    fig, ax = plt.subplots()
    ax.plot(rl_equity, label="RL")
    ax.plot(benchmark_equity, label="Benchmark")
    ax.legend()
    st.pyplot(fig)